### ISSUE TITLE
CashbackHack Remain amount is incorrect for round purchase amounts

### ISSUE THREAD

**Issue by Anna-Omelchenko** [Anna-Omelchenko/aqa-basics#3]
**Steps to reproduce**
1. Create an instance of CashbackHackService with default constructor
2. Call `int remain(int amount)` method with `amount = 1000` (or other "round thousand" amount e.g. 2000, 5000, 12000 etc.)

**Expected result**
`CashbackHackService.remain(int amount)` should return 0 for `amount = 1000`

**Actual result**
`CashbackHackService.remain(1000)` returns 1000

> Expected :0
> Actual   :1000
> <Click to see difference>
> 
> java.lang.AssertionError: expected [0] but found [1000]
> 	at org.testng.Assert.fail(Assert.java:110)
> 	at org.testng.Assert.failNotEquals(Assert.java:1413)
> 	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
> 	at org.testng.Assert.assertEquals(Assert.java:131)
> 	at org.testng.Assert.assertEquals(Assert.java:1240)
> 	at org.testng.Assert.assertEquals(Assert.java:1274)
> 	at ru.netology.cashback.CashbackHackServiceTest.testRoundAmount(CashbackHackServiceTest.java:18)
> 	at ...

**Environment**
- OS: Windows 10 Pro, 64-bit
- Java 11
- Testing framework: TestNG
- PR: #1

**Comment by Anna-Omelchenko** [comment]
Tests execution report:
[aqa-basics_tests_report.zip](https://github.com/Anna-Omelchenko/aqa-basics/files/13322809/aqa-basics_tests_report.zip)
